name: Run Terraform

on:
  push:
    branches:
      - main
  workflow_dispatch:
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.MY_AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.MY_AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: "us-east-1"
  MY_AWS_SSH_ED_KEY: ${{secrets.MY_AWS_SSH_ED_KEY}}
  # CONFIGURE YOUR TERRAFORM CLOUD TOKEN
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.MY_NEW_TF_TOKEN }}
      - name: Run Terraform Init
        run: terraform init
        working-directory: .
      - name: Run Terraform Plan
        run: terraform plan -var-file var.tfvars
        working-directory: .
      - name: Run Terraform Apply
        run: terraform apply -var-file var.tfvars
        working-directory: .